/* UPDATE BAZAR_ItemMaster SET ITEMNAME='moong dal 5 RS',RATE1=42.0000,MRP=60.0000,PACKINGTYPE='CARTON',  
 TOTALITEMSINPACK=12,CATEGORY='NAMKEEN'  ,[DETAILS]='moong dal 5 RS' WHERE ITEMID=1
 
 SELECT * FROM BAZAR_ItemMaster ORDER BY ITEMID
 */ 
 --** USP_Update_ItemDetails_BAZAR can be removed. (01-Aug-26)
 ALTER Procedure DBO.USP_Update_ItemDetails_BAZAR_NEW
@ID as varchar(30),  
@ITEMNAME as varchar(50),  
@MRP as Money,  
@RATE1 as Money,  
@RATE2 as Money,  
@RATE3 as Money,  
--@RATE1_CONDITION as VARCHAR(10),  
--@RATE2_CONDITION as VARCHAR(10),  
--@RATE3_CONDITION as VARCHAR(10),  
@PACKINGTYPE AS varchar(20),  
@TOTALITEMSINPACK AS varchar(10),  
--@TOTALITEMSINCARTON as varchar(10),  
@CATEGORY as varchar(30),  
@DESCRIPTION AS varchar(100),  
@IMAGEURL AS VARCHAR(300),
@SHOPNAME AS varchar(100),
@STOCK AS INT,
@STATUS AS VARCHAR(15) = 'Active'
AS             
BEGIN  
 --declare @ImageURL as varchar(50)  
 --set @ImageURL = (Select top 1 FieldValue from tblAllMasterData where FieldType='ImageServerURL')  
 -- for LINE items from factory.
	Declare @ITEMCODE as INT
  IF @SHOPNAME='LINE_ITEMS'
  BEGIN
		 if @ID > 0   
		 BEGIN  
		 UPDATE BELL_ItemMaster SET ITEMNAME=@ITEMNAME,MRP=@MRP,RATE1=@RATE1,RATE2=@RATE2,RATE3=@RATE3,
		 PACKINGTYPE=@PACKINGTYPE, ACTIONDATE=GETDATE(), STATUS=@STATUS,
		 TOTALITEMSINPACK=@TOTALITEMSINPACK,CATEGORY=@CATEGORY, STOCK=@STOCK, 
		 [DETAILS]=@DESCRIPTION WHERE ITEMID=@ID
		 --ITEMNAME=@ITEMNAME  
		 END  
		 ELSE  
		 BEGIN  
			Select @ITEMCODE = ISNULL(MAX(ITEMCODE),0)+1 from BELL_ItemMaster
			--TODO: NEED TO ADD USERNAME,MANUFACTURE,OFFERAVAILABLE,DISCOUNTPERCENT, OFFERITEMNAME, OFFERPAKS
		  INSERT INTO BELL_ItemMaster (ITEMCODE,ITEMNAME,MRP,RATE1,RATE2,RATE3,STOCK,
			PACKINGTYPE,TOTALITEMSINPACK,CATEGORY,[DETAILS],ImageUrl,DISCOUNTPERCENT,STATUS,ACTIONDATE)  
		  VALUES(@ITEMCODE ,@ITEMNAME,@MRP,@RATE1,@RATE2,@RATE3,@STOCK,
			@PACKINGTYPE,@TOTALITEMSINPACK,@CATEGORY,@DESCRIPTION,@IMAGEURL,0,'ACTIVE',GETDATE()) 
		 END  
	END
	ELSE  --FOR REGULAR SHOPS FLOW 
	BEGIN
		 if @ID > 0   
		 BEGIN  
		 --OLD TABLE TBLITEMMASTER USED FOR ZION 
		 UPDATE BAZAR_ItemMaster SET ITEMNAME=@ITEMNAME,MRP=@MRP,RATE1=@RATE1,RATE2=@RATE2,RATE3=@RATE3,
		 --RATE1_CONDITION=@RATE1_CONDITION,RATE2_CONDITION=@RATE2_CONDITION,RATE3_CONDITION=@RATE3_CONDITION,
		 PACKINGTYPE=@PACKINGTYPE, ACTIONDATE=GETDATE(), STATUS=@STATUS,
		 TOTALITEMSINPACK=@TOTALITEMSINPACK,CATEGORY=@CATEGORY, STOCK=@STOCK, 
		 [DETAILS]=@DESCRIPTION WHERE ITEMID=@ID
		 --ITEMNAME=@ITEMNAME  
		 --(this is to update for all Shops) TODO: after confirmation can be updated for selected Shops
		 --ITEMID=@ID
		 --IMAGEURL=@IMAGEURL,  
		 END  
		 ELSE  
		 BEGIN  
			Select @ITEMCODE = ISNULL(MAX(ITEMCODE),0)+1 from BAZAR_ItemMaster
			--TODO: NEED TO ADD USERNAME,MANUFACTURE,OFFERAVAILABLE,DISCOUNTPERCENT, OFFERITEMNAME, OFFERPAKS
		  INSERT INTO BAZAR_ItemMaster (ITEMCODE,ITEMNAME,MRP,RATE1,RATE2,RATE3,STOCK,
			PACKINGTYPE,TOTALITEMSINPACK,CATEGORY,[DETAILS],ImageUrl,SHOPNAME,DISCOUNTPERCENT,STATUS,ACTIONDATE)  
		  VALUES(@ITEMCODE ,@ITEMNAME,@MRP,@RATE1,@RATE2,@RATE3,@STOCK,
			@PACKINGTYPE,@TOTALITEMSINPACK,@CATEGORY,@DESCRIPTION,@IMAGEURL,@SHOPNAME,0,'ACTIVE',GETDATE()) 
		 END  
	END  	

END  