-- select * from BELL_APP_SHOPS_VISIT_INFO where line='HANAMKONDA' and orderdate='2026-Apr-25'


BELL_UPSERT_MOBILE_SHOP_VISITING_INFO_JSON
'[{"ID":13,"LINE":"HANAMKONDA","AREA":"BHEEMARAM","SHOPNAME":"KRISHNA SAI B/K (HNK) (BEMARRAM)","SALESMAN":"GOPAL.P","CUSTOMER":null,"MOBILE":null,"ORDERDATE":"2026-04-25T00:00:00","SHOP_VISIT_STATUS":"BILLED","BILLING_START_DATE":"2026-04-27T12:26:10","BILLING_END_DATE":"2026-04-27T12:33:57"},{"ID":15,"ACTIONDATE":"0001-01-01T00:00:00","LINE":"HANAMKONDA","AREA":"BHEEMARAM","SHOPNAME":"SRI LAXMI G/S(HNK)(BHEEMARAM)","SALESMAN":"GOPAL.P","CUSTOMER":null,"MOBILE":null,"ORDERDATE":"2026-04-25T00:00:00","SHOP_VISIT_STATUS":"NO CASH","BILLING_START_DATE":"0001-01-01T00:00:00","BILLING_END_DATE":"2026-04-27T18:37:43"}]'

--working with json data both Insert and Update working 06-Apr-26
ALTER procedure BELL_UPSERT_MOBILE_SHOP_VISITING_INFO_JSON
    @JsonData NVARCHAR(MAX)
AS                         
BEGIN            
SET @JsonData = REPLACE(@JsonData,'\','')
  print '@JSONDATA=' + @JsonData

    ;WITH JSON_DATA AS (
        SELECT 
            LINE,
            AREA,
            SHOPNAME,
            SHOP_VISIT_STATUS,
            SALESMAN,
            ORDERDATE,
            BILLING_START_DATE,
            BILLING_END_DATE
        FROM OPENJSON(@JsonData)
        WITH (
            LINE  VARCHAR(50),
            AREA VARCHAR(50),
            SHOPNAME  VARCHAR(100),
            SHOP_VISIT_STATUS  VARCHAR(30),
            SALESMAN   VARCHAR(30),
            ORDERDATE   DATETIME2,
            BILLING_START_DATE DATETIME2,
            BILLING_END_DATE DATETIME2
        )
    )
MERGE BELL_APP_SHOPS_VISIT_INFO AS target
    USING JSON_DATA AS source
        ON target.LINE = source.LINE
       AND target.AREA = source.AREA
       AND target.SHOPNAME     = source.SHOPNAME
       AND target.SALESMAN     = source.SALESMAN
       AND target.ORDERDATE = source.ORDERDATE 
    WHEN MATCHED THEN
        UPDATE SET 
            target.SHOP_VISIT_STATUS   = source.SHOP_VISIT_STATUS,target.BILLING_START_DATE=source.BILLING_START_DATE,
            target.BILLING_END_DATE=source.BILLING_END_DATE, target.ACTIONDATE = GETDATE()
            --target.BILLING_START_DATE=IIF(source.BILLING_START_DATE LIKE '0001-01-01%', GETDATE(),source.BILLING_START_DATE),
            --target.BILLING_END_DATE=IIF(source.BILLING_END_DATE LIKE '0001-01-01%', GETDATE(),source.BILLING_END_DATE),
    WHEN NOT MATCHED THEN
        INSERT (LINE,AREA,SHOPNAME,SHOP_VISIT_STATUS,SALESMAN,ORDERDATE, ACTIONDATE,BILLING_START_DATE,BILLING_END_DATE)
        VALUES (source.LINE, source.AREA, source.SHOPNAME, source.SHOP_VISIT_STATUS,source.SALESMAN
        ,source.ORDERDATE, GETDATE(),source.BILLING_START_DATE,source.BILLING_END_DATE);

        -- BELOW CODE IS WORKING BUT NOT USING HERE.
        --IIF(source.BILLING_START_DATE LIKE '0001-01-01%', GETDATE(),source.BILLING_START_DATE),
       --IIF(source.BILLING_END_DATE LIKE '0001-01-01%', GETDATE(),source.BILLING_END_DATE));

   SELECT 1 AS RESULT            
END 
GO

CREATE procedure BELL_UPSERT_MOBILE_SHOP_VISITING_INFO
@LINE as varchar(50),
@AREA as varchar(50),
@SHOPNAME AS VARCHAR(100),            
@ORDERDATE as DATETIME,
@SHOP_VISIT_STATUS AS VARCHAR(50),            
@SALESMAN AS nvarchar(30)=''
AS                         
BEGIN            

  iF (SELECT COUNT(1) FROM BELL_APP_SHOPS_VISIT_INFO WHERE LINE=@LINE AND AREA=@AREA AND SHOPNAME=@SHOPNAME         
     AND ORDERDATE = @ORDERDATE) = 0              
 BEGIN            
    insert into BELL_APP_SHOPS_VISIT_INFO
    (LINE,AREA,SHOPNAME,SHOP_VISIT_STATUS,SALESMAN,ORDERDATE) VALUES (
    @LINE,@AREA,@SHOPNAME,@SHOP_VISIT_STATUS,@SALESMAN,@ORDERDATE)   
END
 ELSE            
 BEGIN            
        UPDATE BELL_APP_SHOPS_VISIT_INFO SET  LINE=@LINE,AREA=@AREA,SHOPNAME=@SHOPNAME,SALESMAN=@SALESMAN,
        SHOP_VISIT_STATUS=@SHOP_VISIT_STATUS,ORDERDATE=@ORDERDATE, ACTIONDATE=GETDATE()
      WHERE LINE=@LINE AND AREA=@AREA AND SHOPNAME=@SHOPNAME AND ORDERDATE=@ORDERDATE 
 END
   SELECT 1 AS RESULT            
END 