-- BELL_GET_CASH_INOUT_CHANGE_LOG 'all','14-Mar-2025'
-- BELL_GET_CASH_INOUT_CHANGE_LOG 'all','16-Mar-2025'

alter Procedure BELL_GET_CASH_INOUT_CHANGE_LOG
@TRANSTYPE as varchar(3) = null,  
@PAIDDATE AS DATE = null  
AS               
BEGIN    
 Declare @strQuery as varchar(1500)              
 Declare @strWhereQuery as varchar(500)  
 --PRINT @FromDate  
 IF (ISNULL(@PAIDDATE,'') <> '' )  
 BEGIN  
   SELECT CATEGORY, PURPOSE,PAIDTOPERSON,AMOUNT AS AMOUNT_OLD,AMOUNT_NEW,USERNAME,TRANSTYPE,
	 ActionDate, FORMAT(PAIDDATE, 'dd-MMM-yyyy', 'en-US') as PAIDDATE FROM BELL_DAILYCASHFLOW_LOG 
   WHERE TRANSTYPE = (case lower(@TRANSTYPE) when 'all' then TRANSTYPE ELSE @TRANSTYPE END)  
   AND CONVERT(varchar(10),PAIDDATE,102) = CONVERT(varchar(10),@PAIDDATE,102) ORDER BY ACTIONDATE,CATEGORY,PURPOSE,PAIDTOPERSON   
END  

END    