ALTER procedure BELL_UPD_AREA_BY_LINE_SHOP    
AS                   
BEGIN      
 DECLARE @LINE VARCHAR(50), @AREA VARCHAR(50), @SHOP VARCHAR(100)    
 DECLARE db_cursor CURSOR FOR     
 --SELECT LINE,AREA,SHOPNAME FROM Bell_Cust_Master  order by LINE    
    SELECT A.LINE,A.AREA,A.SHOPNAME FROM Bell_Cust_Master A WHERE 
	--LINE IN (SELECT AREA FROM BHAVANI_ER_BILLS WHERE AREA_LINE IS NULL) AND
	SHOPNAME IN (SELECT SHOPNAME FROM BHAVANI_ER_BILLS WHERE AREA_LINE IS NULL)

OPEN db_cursor      
FETCH NEXT FROM db_cursor INTO @LINE,@AREA,@SHOP    
WHILE @@FETCH_STATUS = 0      
BEGIN      
  --UPDATE bhavani_ER_Bills22 SET AREA=@AREA WHERE LINE=@LINE AND SHOPNAME=@SHOP    
  UPDATE bhavani_ER_Bills SET AREA_LINE=@AREA WHERE AREA=@LINE AND SHOPNAME=@SHOP   AND AREA_LINE IS NULL  
    
    FETCH NEXT FROM db_cursor INTO @LINE,@AREA,@SHOP    
END     
CLOSE db_cursor      
DEALLOCATE db_cursor    
    
END 