--select * from bhavani_ER_Bills  where billdate = '2025-Jan-15'
--update bhavani_ER_Bills  set PRATE=RATE-RATE*0.05 WHERE PRATE ISNULL

alter procedure BELL_INC_UPD_Bills  
@AREA as varchar(30),  
@SHOP AS VARCHAR(50),  
@BILLDATE as DATE,  
@ITEMCODE AS integer,  
@ITEMNAME AS VARCHAR(30),  
@PRICE AS VARCHAR(5),  
@QTY AS VARCHAR(10),  
@PACKETS AS integer,  
@BILLNUMBER AS INTeger,  
@AMOUNT AS integer,  
@USERNAME AS VARCHAR(30),  
@result int OUTPUT  
  
AS               
BEGIN  
 --IF NOT EXISTS(SELECT SHOPNAME FROM Bell_Cust_Master WHERE AREA=@AREA AND SHOPNAME=@SHOP)  
 --BEGIN  
 -- INSERT INTO Bell_Cust_Master (CUSTID,AREA,SHOPNAME,[STATUS]) VALUES(0,@AREA,@SHOP,'Active')  
 --END  
 --set @BILLDATE = FORMAT(@BILLDATE, 'dd-MMM-yyyy', 'en-US')  
  set @BILLDATE = CONVERT(varchar(10),@BILLDATE,101)  
  DECLARE @PRATE AS MONEY
  SELECT @PRATE=ISNULL(PRATE,RATE1) FROM Bell_ItemMaster WHERE   ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME

  iF (SELECT COUNT(1) FROM bhavani_ER_Bills WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND AREA=@AREA AND SHOPNAME=@SHOP  
     AND BILLNUMBER=@BILLNUMBER AND CONVERT(varchar(10),BILLDATE,101) = @BILLDATE) = 0   
 BEGIN  
   insert into bhavani_ER_Bills (ITEMCODE,ITEMNAME,RATE,PACKETS,QTY,AMOUNT,BILLNUMBER,BILLDATE,AREA,SHOPNAME,USERNAME,PRATE)   
   values(@ITEMCODE,@ITEMNAME,@PRICE,@PACKETS,@QTY,@AMOUNT,@BILLNUMBER,@BILLDATE,@AREA,@SHOP,@USERNAME,@PRATE)  
  END  
  ELSE  
  BEGIN  
      UPDATE bhavani_ER_Bills SET RATE=@PRICE,PACKETS=@PACKETS,QTY=@QTY,AMOUNT=@AMOUNT,USERNAME=@USERNAME WHERE  
        ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND AREA=@AREA AND SHOPNAME=@SHOP  
        AND BILLNUMBER=@BILLNUMBER AND CONVERT(varchar(10),BILLDATE,101) = @BILLDATE  
  END  
    SET @result = 1  
   SELECT @result AS RESULT  
END  