
--TO UPDATE PURCHASE RATE AND MINIMUM ORDER ALERT VALUE FROM WEB APP.
ALTER PROCEDURE  BELL_UPD_ITEMS_PRATE_MINORDER  
@ITEMCODE AS INTEGER,
@PRATE AS MONEY,  
@MINORDERALERT AS INTEGER,  
@USERNAME AS VARCHAR(30)      
AS                   
BEGIN          
  
    UPDATE Bell_ItemMaster SET PRATE=@PRATE, MINORDERALERT=@MINORDERALERT,USERNAME=@USERNAME,ActionDate=GETDATE()      
    WHERE ITEMCODE=@ITEMCODE    -- AND ITEMNAME=@ITEMNAME
        
END   