-- CREATED FOR LOCAL TO WEB BULK COPY
CREATE PROCEDURE BELL_INS_UPD_CASH_TRANS_LOCA2WEB
@CASHID INT,
@PAIDDATE AS DATE,
@CATEGORY AS VARCHAR(50),
@PURPOSE AS VARCHAR(50),
@PAIDTOPERSON AS VARCHAR(50),
@AMOUNT MONEY,
@PAYMENT_MODE AS VARCHAR(10),
@MOREDETAILS  AS VARCHAR(250),
@FILEINFO AS VARCHAR(50),
@TRANSTYPE AS VARCHAR(10),
@STATUS  AS VARCHAR(10),
@seq_no INT,
@USERNAME AS VARCHAR(50),
@result int OUTPUT ,
@due_date as varchar(12) = ''  -- newly added on 19-Oct-25 for local to web copy

AS
BEGIN
 IF @CASHID = 0 
 begin    
			Insert into BELL_DAILYCASHFLOW(PAIDDATE,CATEGORY,PURPOSE,PAIDTOPERSON,AMOUNT,PAYMENT_MODE,MOREDETAILS,TRANSTYPE,[STATUS],USERNAME,FILEINFO,seq_no,due_date) 
			VALUES(@PAIDDATE,@CATEGORY,@PURPOSE,@PAIDTOPERSON,@AMOUNT,@PAYMENT_MODE,@MOREDETAILS,@TRANSTYPE,@STATUS,@USERNAME,@FILEINFO,@seq_no,
			convert(varchar(12),@due_date,101) ) 
			--set @result = (SELECT SCOPE_IDENTITY())
			set @result = (SELECT @@IDENTITY)
			 SELECT @result AS RESULT    
	END 
--else																						?
--begin
	--TODO updated all values and actiondate
	--UPDATE BELL_DAILYCASHFLOW SET AMOUNT=@AMOUNT WHERE ID=@CASHID
--end
End
go
