/*
--ALTER TABLE Bell_LS_ORDERS ALTER COLUMN WEBSYNCED VARCHAR(15)
ALTER TABLE Bell_LS ALTER COLUMN STATUS VARCHAR(30)

select * from Bell_LS where area='kothaguda' and billdate='2026-Mar-30'
select * from Bell_LS where USERNAME='From_Mobile'
--UPDATE Bell_LS SET R_B=0 where area='kothaguda' and billdate='2026-Mar-30'

SELECT ISJSON('{"test":1}') AS IsJsonSupported;
SELECT * 
FROM OPENJSON('[{"BillDate":"2026-03-30","AREA":"kothaguda","ITEMCODE":1,"ITEMNAME":"khara 5 RS","RET_PAK":5,"DAM_PAK":0,"USERNAME":"From_Mobile","SALESMAN":"TEJASWINI"}]')
WITH (
    BillDate DATE,
    AREA VARCHAR(30),
    ITEMCODE INT,
    ITEMNAME VARCHAR(30),
    RET_PAK INT,
    DAM_PAK INT,
    USERNAME VARCHAR(30),
    SALESMAN VARCHAR(30)
);

SELECT REPLACE('CHECK','E','e')

BELL_UPDATE_LS_RETURN_ITEMS_MOBILE_JSON '[{"BillDate":"2026-03-30","AREA":"kothaguda","ITEMCODE":1,"ITEMNAME":"khara 5 RS","RET_PAK":5,"DAM_PAK":0,"USERNAME":"From_Mobile","SALESMAN":"TEJASWINI"}]'

BELL_UPDATE_LS_RETURN_ITEMS_MOBILE_JSON '[{"ITEMCODE":1,"ITEMNAME":"khara 5 RS","AVAILABLE_PAKS":156,"LINE":"KOTHAGUDA","SALESMAN":"GOPAL.P","BillDate":"2026-03-30"},
{"ITEMCODE":2,"ITEMNAME":"moong dal 5 RS","AVAILABLE_PAKS":264,"LINE":"KOTHAGUDA","SALESMAN":"GOPAL.P","BillDate":"2026-03-30"},
{"ITEMCODE":5,"ITEMNAME":"ABCD 5 RS","AVAILABLE_PAKS":48,"LINE":"KOTHAGUDA","SALESMAN":"GOPAL.P","BillDate":"2026-03-30"},
{"ITEMCODE":6,"ITEMNAME":"Animal 5 RS","AVAILABLE_PAKS":48,"LINE":"KOTHAGUDA","SALESMAN":"GOPAL.P","BillDate":"2026-03-30"},
{"ITEMCODE":7,"ITEMNAME":"Sticks 5 RS","AVAILABLE_PAKS":36,"LINE":"KOTHAGUDA","SALESMAN":"GOPAL.P","BillDate":"2026-03-30"},
{"ITEMCODE":8,"ITEMNAME":"WHEELS 5 RS","AVAILABLE_PAKS":48,"LINE":"KOTHAGUDA","SALESMAN":"GOPAL.P","BillDate":"2026-03-30"},
{"ITEMCODE":9,"ITEMNAME":"Soya sticks 5 RS","AVAILABLE_PAKS":84,"LINE":"KOTHAGUDA","SALESMAN":"GOPAL.P","BillDate":"2026-03-30"}]'


[{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"1","ITEMNAME":"khara 5 RS","RATE":"42","PACKING_QTY":"5C (12)","QTY":"60","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"2","ITEMNAME":"moong dal 5 RS","RATE":"42","PACKING_QTY":"5C (12)","QTY":"60","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"3","ITEMNAME":"Alubujiya 5 RS","RATE":"42","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"4","ITEMNAME":"Bhoondi 5 RS","RATE":"42","PACKING_QTY":"2C (12)","QTY":"24","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"5","ITEMNAME":"ABCD 5 RS","RATE":"43","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"6","ITEMNAME":"Animal 5 RS","RATE":"43","PACKI
NG_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"7","ITEMNAME":"Sticks 5 RS","RATE":"43","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"8","ITEMNAME":"WHEELS 5 RS","RATE":"43","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"9","ITEMNAME":"Soya sticks 5 RS","RATE":"42","PACKING_QTY":"2C (12)","QTY":"24","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"10","ITEMNAME":"SEV MURMURA 5 RS","RATE":"42","PACKING_QTY":"2C (12)","QTY":"24","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"13","ITEMNAME":"Khara 700 GM","RATE":"110","PACKING_QTY":"1C (10)","QTY":"10","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES"
,"ITEMCODE":"14","ITEMNAME":"Khara 325 GM","RATE":"55","PACKING_QTY":"3C (20)","QTY":"60","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"15","ITEMNAME":"Bhoondhi 325 GM","RATE":"55","PACKING_QTY":"1C (20)","QTY":"20","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"21","ITEMNAME":"Khara 10 RS","RATE":"7","PACKING_QTY":"1B (70)","QTY":"70","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"40","ITEMNAME":"CHEKODI 250GM","RATE":"40","PACKING_QTY":"1C (20)","QTY":"20","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"42","ITEMNAME":"KHARA 150GM","RATE":"25","PACKING_QTY":"1P (1)","QTY":"1","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"43","ITEMNAME":"KHARA 500 GM","RATE":"85","PACKING_QTY":"1C (20)","QTY":"20","USERNAME":"ORDERS"},{"BillDate":"
2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"60","ITEMNAME":"ROUND CHIKKY","RATE":"20","PACKING_QTY":"14K (10)","QTY":"140","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"62","ITEMNAME":"Chikky 5 RS","RATE":"180","PACKING_QTY":"2C (6)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"64","ITEMNAME":"12 pics Chikky","RATE":"8.5","PACKING_QTY":"62D (12)","QTY":"744","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"74","ITEMNAME":"Mysorepak 5 Rs","RATE":"130","PACKING_QTY":"2C (6)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"75","ITEMNAME":"Kajapuri 5 Rs","RATE":"115","PACKING_QTY":"2C (6)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"81","ITEMNAME":"BHADUSHA 5 RS","RATE":"135","
PACKING_QTY":"1C (6)","QTY":"6","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"82","ITEMNAME":"NICE COVA PKT","RATE":"36","PACKING_QTY":"1C (40)","QTY":"40","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"83","ITEMNAME":"NICE COVA JAR","RATE":"175","PACKING_QTY":"1C (8)","QTY":"8","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"85","ITEMNAME":"BELL SOANPAPID 250MRP","RATE":"180","PACKING_QTY":"2C (6)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"97","ITEMNAME":"CHIIKKY LADDU 5RS","RATE":"40","PACKING_QTY":"10P (1)","QTY":"10","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"103","ITEMNAME":"MARIE SUMO 5 RS","RATE":"41.66","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JEND
A (HNK) DIRECT SALES","ITEMCODE":"106","ITEMNAME":"HI-FUN(CREAM)5 RS","RATE":"37.5","PACKING_QTY":"1C (16)","QTY":"16","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"108","ITEMNAME":"OSMANIYA 3 RS","RATE":"37","PACKING_QTY":"1C (30)","QTY":"30","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"123","ITEMNAME":"OSMANIYA BIS JAR 5RS","RATE":"155","PACKING_QTY":"1C (6)","QTY":"6","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"125","ITEMNAME":"ROSE WAFER 1RS","RATE":"40","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"129","ITEMNAME":"SALTINO 5RS","RATE":"47","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"130","ITEMNAME":"BELL MILK COOKIES 5RS","RATE":"45","PACKING_QTY":"1
C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"131","ITEMNAME":"BELL RUSK 10RS","RATE":"7.3","PACKING_QTY":"1C (50)","QTY":"50","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"132","ITEMNAME":"BELL FRUIT COOKIES 5RS","RATE":"45","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"141","ITEMNAME":"ROSE RAAGI BISCATE","RATE":"35.5","PACKING_QTY":"2C (24)","QTY":"48","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"142","ITEMNAME":"TEA TIME 5RS","RATE":"140","PACKING_QTY":"1C (6)","QTY":"6","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"160","ITEMNAME":"BUTTER FUN 50NP","RATE":"46","PACKING_QTY":"1C (34)","QTY":"34","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK)
 DIRECT SALES","ITEMCODE":"168","ITEMNAME":"FRUITO POP JAR 2RS","RATE":"97","PACKING_QTY":"2C (12)","QTY":"24","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"170","ITEMNAME":"CHACO DAIRY BLITZ 5RS","RATE":"96","PACKING_QTY":"1C (18)","QTY":"18","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"173","ITEMNAME":"TRUFFELLO JAR (12P) 5RS","RATE":"160","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"174","ITEMNAME":"TRUFFELLO (24P) 5RS","RATE":"66","PACKING_QTY":"1C (24)","QTY":"24","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"214","ITEMNAME":"NOU STAR JAR 5RS","RATE":"135","PACKING_QTY":"1C (18)","QTY":"18","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"215","ITEMNAME":"MILKY STAR 5RS","RATE":"135","PACKI
NG_QTY":"1C (18)","QTY":"18","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"252","ITEMNAME":"ECLACHI ECLAIRS PKT 1/-","RATE":"53","PACKING_QTY":"1C (36)","QTY":"36","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"254","ITEMNAME":"ECLAIRS 50 NP","RATE":"28","PACKING_QTY":"1C (40)","QTY":"40","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"300","ITEMNAME":"CAKE 1RS","RATE":"15","PACKING_QTY":"2C (40)","QTY":"80","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"301","ITEMNAME":"CAKE TIME 5RS","RATE":"146","PACKING_QTY":"1C (6)","QTY":"6","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"302","ITEMNAME":"TWERK 5RS","RATE":"100","PACKING_QTY":"1C (16)","QTY":"16","USERNAME":"ORDERS"}]

BELL_UPDATE_LS_RETURN_ITEMS_MOBILE_JSON   
'[{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"1","ITEMNAME":"khara 5 RS","RATE":"42","PACKING_QTY":"5C (12)","QTY":"60","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"2","ITEMNAME":"moong dal 5 RS","RATE":"42","PACKING_QTY":"5C (12)","QTY":"60","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"3","ITEMNAME":"Alubujiya 5 RS","RATE":"42","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"4","ITEMNAME":"Bhoondi 5 RS","RATE":"42","PACKING_QTY":"2C (12)","QTY":"24","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"5","ITEMNAME":"ABCD 5 RS","RATE":"43","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},
{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"6","ITEMNAME":"Animal 5 RS","RATE":"43","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"7","ITEMNAME":"Sticks 5 RS","RATE":"43","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"8","ITEMNAME":"WHEELS 5 RS","RATE":"43","PACKING_QTY":"1C (12)","QTY":"12","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"9","ITEMNAME":"Soya sticks 5 RS","RATE":"42","PACKING_QTY":"2C (12)","QTY":"24","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"10","ITEMNAME":"SEV MURMURA 5 RS","RATE":"42","PACKING_QTY":"2C (12)","QTY":"24","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES","ITEMCODE":"13","ITEMNAME":"Khara 700 GM","RATE":"110","PACKING_QTY":"1C (10)","QTY":"10","USERNAME":"ORDERS"},{"BillDate":"2026-09-02","LINE":"HNK KOTHUR JENDA (HNK) DIRECT SALES"
,"ITEMCODE":"14","ITEMNAME":"Khara 325 GM","RATE":"55","PACKING_QTY":"3C (20)","QTY":"60","USERNAME":"ORDERS"}]',
'ORDERS','HNK KOTHUR JENDA (HNK) DIRECT SALES','2026-09-02'  


*/  
ALTER PROCEDURE BELL_UPDATE_LS_RETURN_ITEMS_MOBILE_JSON  
    @JsonData NVARCHAR(MAX),  
    @OPERATION VARCHAR(30),  
    @LINE VARCHAR(50),  
    @ORDERDATE DATE  
AS  
BEGIN  
    SET NOCOUNT ON;  
  
    SET @JsonData = REPLACE(@JsonData,'\','')  
  
    -- MODIFIED 'LS' CODE ON 31-AUG-26  TO ADD R_B IN UPDATE 
    IF @OPERATION = 'LS'  
    BEGIN  
            -- Parse JSON into a table variable  
            ;WITH JsonData AS (  
                SELECT   
                    BILLDATE,  
                    LINE,  
                    ITEMCODE,  
                    ITEMNAME,  
                    RATE,  
                    QTY,  
                    T_B,  
                    R_B,  
                    USERNAME,  
                    SALESMAN  
                FROM OPENJSON(@JsonData)  
                WITH (  
                    BILLDATE DATE,  
                    LINE  VARCHAR(50),  
                    ITEMCODE   INT,  
                    ITEMNAME  VARCHAR(50),  
                    RATE MONEY,  
                    QTY VARCHAR(20),  
                    T_B  INT,  
                    R_B  INT,  
                    USERNAME  VARCHAR(50),  
                    SALESMAN VARCHAR(50)  
                )  
            )  
            -- commented on 12-Jul-26 , need to test  
            --UPDATE Bell_LS SET USERNAME = p.USERNAME, [STATUS] = p.SALESMAN, R_B = p.T_B,ACTIONDATE = GETDATE()  
            --FROM Bell_LS b  INNER JOIN JsonData p ON b.ITEMCODE = p.ITEMCODE AND b.ITEMNAME = p.ITEMNAME  
            --   AND b.AREA = p.LINE  AND b.BILLDATE = p.BillDate;  
  
             MERGE BELL_LS AS target  
            USING JsonData AS source  
               ON target.AREA = source.LINE  
               AND target.BILLDATE = source.BILLDATE   
              -- AND target.ITEMNAME = source.ITEMNAME  
               AND target.ITEMCODE = source.ITEMCODE  
            WHEN MATCHED THEN  
                UPDATE SET   
                    target.T_B = source.T_B,target.R_B = source.R_B, target.QTY=source.QTY,STATUS='VERIFIED',  
                    target.ITEMNAME = source.ITEMNAME, target.RATE=source.RATE, 
                    target.USERNAME=source.USERNAME,target.ACTIONDATE = GETDATE()  
            WHEN NOT MATCHED AND source.T_B > 0 THEN  
            INSERT (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B,R_B,[STATUS])   
           VALUES(source.ITEMCODE,source.ITEMNAME,source.RATE,source.QTY,source.BILLDATE,source.LINE,source.USERNAME,source.T_B,R_B,'VERIFIED');  
        END  
        ELSE IF @OPERATION = 'ORDERS'  
        BEGIN          
            --** USING WEBSYNCED TO MAKE SURE IT IS INSERTED FROM MOBILE APP.  OTHERWISE IT WILL DELETE OTHER RECORDS.  
            ;WITH JsonData AS (  
                SELECT   
                    BillDate,  
                    LINE,  
                    ITEMCODE,  
                    ITEMNAME,  
                    RATE,  
                    PACKING_QTY,  
                    QTY,  
                    'ORDERS' as USERNAME,  
                    SALESMAN  
                FROM OPENJSON(@JsonData)  
                WITH (  
                    BillDate  DATE,  
                    LINE  VARCHAR(50),  
                    ITEMCODE  INT,  
                    ITEMNAME VARCHAR(50),  
                    RATE VARCHAR(20),  
                    PACKING_QTY  VARCHAR(20),  
                    QTY  INT,  
                    USERNAME  VARCHAR(50),  
                    SALESMAN  VARCHAR(50)  
                )  
            )  
            --INSERT INTO  Bell_LS_ORDERS (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B,WEBSYNCED)   
           --SELECT J.ITEMCODE,J.ITEMNAME,J.RATE,J.AVAILABLE_PAKS,J.BILLDATE,J.LINE,J.USERNAME,J.QTY,'From_Mobile' FROM JsonData J  
           MERGE BELL_LS_ORDERS AS target  
            USING JsonData AS source  
               ON target.AREA = source.LINE  
               AND target.BillDate = source.BillDate   
              -- AND target.ITEMNAME = source.ITEMNAME  
               AND target.ITEMCODE = source.ITEMCODE  
            WHEN MATCHED THEN  
                UPDATE SET   
                    target.T_B = source.QTY, target.QTY=source.PACKING_QTY,WEBSYNCED='VERIFIED',  
                     target.ITEMNAME = source.ITEMNAME, target.RATE=source.RATE, 
                    target.USERNAME=source.USERNAME,target.ACTIONDATE = GETDATE()  
            WHEN NOT MATCHED AND source.QTY > 0 THEN  
            INSERT (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B,WEBSYNCED)   
           VALUES(source.ITEMCODE,source.ITEMNAME,source.RATE,source.PACKING_QTY,source.BILLDATE,source.LINE,  
           source.USERNAME,source.QTY,'VERIFIED');  
  
            -- delete all zero QTY items from LS table. -- ADDED ON 10-JUN-26.  
                DELETE from BELL_LS_ORDERS where T_B=0 AND BILLDATE=@ORDERDATE AND AREA=@LINE  
        END  
  
        ELSE IF @OPERATION = 'ORDERS APPROVED'  -- after Approval from VAN Loading Approver, it should also insert into LS table  
        BEGIN          
            --** USING WEBSYNCED TO STORE STATUS AS PENDING/VERIFIED/APPROVED...  
            ;WITH JsonData AS (  
                SELECT   
                BillDate,LINE,ITEMCODE,ITEMNAME,RATE,PACKING_QTY,QTY,'ORDERS' as USERNAME,SALESMAN  
                FROM OPENJSON(@JsonData) WITH ( BillDate  DATE,LINE  VARCHAR(30),ITEMCODE  INT,ITEMNAME VARCHAR(30),  
                    RATE VARCHAR(20),PACKING_QTY  VARCHAR(20),QTY  INT,USERNAME  VARCHAR(30),SALESMAN  VARCHAR(30)  )  
                )  
            --INSERT INTO  Bell_LS_ORDERS (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B,WEBSYNCED)   
           --SELECT J.ITEMCODE,J.ITEMNAME,J.RATE,J.AVAILABLE_PAKS,J.BILLDATE,J.LINE,J.USERNAME,J.QTY,'From_Mobile' FROM JsonData J  
           MERGE BELL_LS_ORDERS AS target  
            USING JsonData AS source  
               ON target.AREA = source.LINE AND target.BillDate = source.BillDate   
               --AND target.ITEMNAME = source.ITEMNAME  
               AND target.ITEMCODE = source.ITEMCODE   
               WHEN MATCHED THEN  
                UPDATE SET   
                    target.T_B = source.QTY, target.QTY=source.PACKING_QTY,target.USERNAME=source.USERNAME,  
                     target.ITEMNAME = source.ITEMNAME,  
                    WEBSYNCED='APPROVED',target.ACTIONDATE = GETDATE()  
            WHEN NOT MATCHED AND source.QTY > 0 THEN  
            INSERT (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B,WEBSYNCED)   
           VALUES(source.ITEMCODE,source.ITEMNAME,source.RATE,source.PACKING_QTY,source.BILLDATE,source.LINE,  
           source.USERNAME,source.QTY,'APPROVED');  
  
           -- TO INSERT/UPDATE INTO BELL_LS TABLE  
           ;WITH JsonData AS (  
                SELECT   
                BillDate,LINE,ITEMCODE,ITEMNAME,RATE,PACKING_QTY,QTY, USERNAME,SALESMAN  
                FROM OPENJSON(@JsonData) WITH ( BillDate  DATE,LINE  VARCHAR(30),ITEMCODE  INT,ITEMNAME VARCHAR(30),  
                    RATE VARCHAR(20),PACKING_QTY  VARCHAR(20),QTY  INT,USERNAME  VARCHAR(30),SALESMAN  VARCHAR(30)  )  
                )  
            --INSERT INTO  Bell_LS_ORDERS (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B,WEBSYNCED)   
           --SELECT J.ITEMCODE,J.ITEMNAME,J.RATE,J.AVAILABLE_PAKS,J.BILLDATE,J.LINE,J.USERNAME,J.QTY,'From_Mobile' FROM JsonData J  
           MERGE BELL_LS AS target  
            USING JsonData AS source  
               ON target.AREA = source.LINE   
               AND target.BillDate = source.BillDate   
               --AND target.ITEMNAME = source.ITEMNAME  
               AND target.ITEMCODE = source.ITEMCODE   
               WHEN MATCHED THEN  
                UPDATE SET   
                    target.T_B = source.QTY, target.QTY=source.PACKING_QTY,target.USERNAME=source.USERNAME,target.STATUS='From_Mobile',  
                     target.ITEMNAME = source.ITEMNAME  
                    ,target.ACTIONDATE = GETDATE()  
                    WHEN NOT MATCHED AND source.QTY > 0 THEN  
               INSERT (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B,STATUS)   
                   VALUES(source.ITEMCODE,source.ITEMNAME,source.RATE,source.PACKING_QTY,source.BILLDATE,source.LINE,  
                   source.USERNAME,source.QTY,'From_Mobile');  
  
                   -- delete all zero QTY items from LS table. -- ADDED ON 4-JUN-26.  
                   DELETE from BELL_LS where T_B=0 AND BILLDATE=@ORDERDATE AND AREA=@LINE  
        END  
    SELECT 1 AS RESULT;  
END  
  GO

--ALTER procedure BELL_UPDATE_LS_RETURN_ITEMS_MOBILE_NEW
--@BILLDATE as DATE,        
--@AREA as varchar(30),        
--@ITEMCODE AS integer,        
--@ITEMNAME AS VARCHAR(30),        
----@QTY AS VARCHAR(15),        
--@RET_PAK AS INTeger,        
--@DAM_PAK AS integer,        
--@USERNAME AS VARCHAR(30),        
--@SALESMAN AS VARCHAR(30)
--AS                     
--BEGIN        
-- set @BILLDATE = CONVERT(varchar(10),@BILLDATE,101)        
 
-- print 'Updating Return items for line=' + @AREA + ' BillDate=' + Cast(@BILLDATE AS VARCHAR(20))

-- UPDATE Bell_LS SET USERNAME=@USERNAME,[STATUS]=@SALESMAN,R_B=@RET_PAK,
-- ACTIONDATE=GETDATE() WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND 
-- AREA=@AREA AND BILLDATE = @BILLDATE
 
-- /*-- UPDATE STOCK WITH RETURN ITEMS 
-- UPDATE BELL_ITEMMASTER SET STOCK=STOCK + @RET_PAK, USERNAME=@USERNAME,ACTIONDATE=GETDATE() 
--    WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME      
--   */     
--   SELECT 1 AS RESULT            
--END 