-- BELL_INC_UPD_ITEMS_STOCK 1,'khara 5 RS',10,'10P(1)','RAJU','OUT','COMPANY','12-31-2024',0      
-- BELL_INC_UPD_ITEMS_STOCK 2002,'Maida',10,'2C(10)','RAJU','IN','COMPANY','12-12-2024',0      
ALTER procedure BELL_INC_UPD_ITEMS_STOCK    
@ITEMCODE AS integer,      
@ITEMNAME as varchar(50),      
@STOCK as INTEGER,      
@QTY AS VARCHAR(15),      
@BILLDATE as DATE,    
@USERNAME AS VARCHAR(30),  
@TRANS_TYPE AS VARCHAR(10),  
@PARTYNAME AS VARCHAR(30),  
@result int OUTPUT      
      
AS                   
BEGIN      
  set @BILLDATE = CONVERT(varchar(10),@BILLDATE,101)
  --declare @BILLDATE as date
  --set @BILLDATE = CONVERT(varchar(10),getdate(),101)

  INSERT INTO Bell_STOCK_ENTRY (ITEMCODE,ITEMNAME,STOCK,QTY,USERNAME,TRANS_TYPE,PARTYNAME,BILLDATE) VALUES(@ITEMCODE,@ITEMNAME,@STOCK,@QTY,@USERNAME,@TRANS_TYPE,@PARTYNAME,@BILLDATE)  
  IF @TRANS_TYPE = 'OUT' -- DEBIT  
  BEGIN  
   UPDATE Bell_ItemMaster SET STOCK=STOCK-@STOCK,USERNAME=@USERNAME,ActionDate=GETDATE() WHERE ITEMNAME=@ITEMNAME AND ITEMCODE=@ITEMCODE    
  END  
  ELSE --IF @TRANS_TYPE='IN'  -- CREDIT  
  BEGIN  
   UPDATE Bell_ItemMaster SET STOCK=STOCK+@STOCK,USERNAME=@USERNAME,ActionDate=GETDATE() WHERE ITEMNAME=@ITEMNAME AND ITEMCODE=@ITEMCODE  
  
    -- This automatic deduction of Raw material for selected Items is not required, can be done manually
    --** TO UPDATE STOCK AUTOMATICALLY FOR ANY RAW MATERIAL (LIKE CORTON) LINKED WITH ACTUAL ITEM.  
    --DECLARE @LINKED_ITEMCODE INT, @LINKED_ITEMNAME AS VARCHAR(50)  
    --SET @LINKED_ITEMCODE = 0  
    ----SET @LINKED_ITEMNAME = ''  
    --SELECT TOP 1 @LINKED_ITEMCODE=RAWMATERIAL_ID,@LINKED_ITEMNAME=RAWMATERIAL_NAME FROM BELL_LINKED_ITEMS WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME  
    --IF @LINKED_ITEMCODE > 0  
    --BEGIN  
    --  INSERT INTO Bell_STOCK_ENTRY (ITEMCODE,ITEMNAME,STOCK,QTY,USERNAME,TRANS_TYPE,PARTYNAME,BILLDATE) VALUES(@LINKED_ITEMCODE,@LINKED_ITEMNAME,@STOCK,@QTY,@USERNAME,'OUT','COMPANY LINKED RM',@BILLDATE)  
    --  UPDATE Bell_ItemMaster SET STOCK=STOCK-@STOCK,USERNAME=@USERNAME,ActionDate=GETDATE() WHERE ITEMNAME=@LINKED_ITEMNAME AND ITEMCODE=@LINKED_ITEMCODE  
    --END  
  END      
 
   SET @result = 1      
  SELECT @result AS RESULT      
END   