select * FROM bhavani_ER_Bills 
WHERE AREA='NEZAR'  AND CONVERT(varchar(10),BILLDATE,102) = CONVERT(varchar(10),'2025.01.16',102)  

select * FROM BELL_LS WHERE AREA='NEZAR'  AND CONVERT(varchar(10),BILLDATE,102) = CONVERT(varchar(10),'2025.01.16',102)  

select A.ITEMNAME,SUM(PACKETS) AS QTY,ISNULL(B.R_B,0) AS RET_QTY,A.AREA  
		,CAST(ISNULL(SUM(AMOUNT)/100.0,0) AS DECIMAL(12,2)) AMOUNT  ,CONVERT(varchar(10),A.BILLDATE,102)
	  FROM bhavani_ER_Bills A LEFT JOIN BELL_LS B ON A.AREA=B.AREA AND A.ITEMCODE=B.ITEMCODE AND A.BILLDATE=B.BILLDATE AND A.ITEMNAME=B.ItemName  
	  where A.AREA='NEZAR' 
	  AND CONVERT(varchar(10),A.BILLDATE,102) = CONVERT(varchar(10),'2025.01.16',102)  
	  GROUP BY A.ITEMCODE,A.ITEMNAME,A.AREA,B.R_B,A.BILLDATE ORDER BY A.ITEMCODE  
	  
-- BELL_GET_LS_ItemsByArea_Date 'ShopWiseTotalSales','BHADRACHALAM','BHARATHI RAJ (BCM)(ASHWAPUR)','15-Jan-2025'  
-- BELL_GET_LS_ItemsByArea_Date 'ShopWiseTotalSales','BAYYARAM ','AMBIKA K/M (BYR)(MRO)','16-Jan-2025'  
-- BELL_GET_LS_ItemsByArea_Date '','BAYYARAM ','','16-Jan-2025'  
-- BELL_GET_LS_ItemsByArea_Date '','NEZAR','','13-Jan-2025'  
alter Procedure BELL_GET_LS_ItemsByArea_Date  
@ReportName as varchar(50) = null,  
@AREA as varchar(30) = null,  
@SHOP as varchar(50) = null , 
@BILLDATE AS DATE = null 
AS               
BEGIN   
IF @ReportName = 'ShopWiseTotalSales'
	BEGIN
		select A.ITEMNAME,PACKETS AS QTY
		--,CAST(ISNULL(AMOUNT,0) AS DECIMAL(12,2)) AMOUNT 
		,A.RATE AS RET_QTY,A.AREA  
		,CAST(ISNULL(AMOUNT/100.0,0) AS DECIMAL(12,2)) AMOUNT      
	  FROM bhavani_ER_Bills A  where A.AREA=@AREA AND CONVERT(varchar(10),A.BILLDATE,102) = CONVERT(varchar(10),@BILLDATE,102)  
	  AND SHOPNAME=@SHOP  ORDER BY A.ITEMCODE  
	END
ELSE
BEGIN
	 IF (ISNULL(@BILLDATE,'') <> '' )  
	 BEGIN  
	  --select A.CUSTID, ITEMNAME,RATE,PACKETS,QTY,AMOUNT,BILLNUMBER, C.SHOPNAME, ISNULL(C.SALESMAN,'') SALESMAN,C.AREA,  
	  --BILLDATE FROM bhavani_ER_Bills A INNER JOIN Bell_Cust_Master C ON C.CUSTID = A.CUSTID   
	  --where C.AREA=@AREA  
	  --AND CONVERT(varchar(10),BILLDATE,102) = CONVERT(varchar(10),@BILLDATE,102)  
		--INNER JOIN Bell_Cust_Master C ON C.CUSTID = A.CUSTID  
  
		select A.ITEMNAME,SUM(PACKETS) AS QTY,ISNULL(B.R_B,0) AS RET_QTY,A.AREA  
		--,SUM(A.AMOUNT) AS AMOUNT,  
		,CAST(ISNULL(SUM(AMOUNT)/100.0,0) AS DECIMAL(12,2)) AMOUNT      
	   --,(select R_B AS RET_QTY2 FROM BELL_LS LS WHERE LS.AREA=@AREA AND CONVERT(varchar(10),LS.BILLDATE,102) = CONVERT(varchar(10),@BILLDATE,102)  
		--AND LS.ITEMCODE=A.ITEMCODE AND LS.ITEMNAME=A.ITEMNAME)  
	  FROM bhavani_ER_Bills A LEFT JOIN BELL_LS B ON A.AREA=B.AREA AND A.ITEMCODE=B.ITEMCODE AND A.BILLDATE=B.BILLDATE AND A.ITEMNAME=B.ItemName  
	  where A.AREA=@AREA AND CONVERT(varchar(10),A.BILLDATE,102) = CONVERT(varchar(10),@BILLDATE,102)  
	  GROUP BY A.ITEMCODE,A.ITEMNAME,A.AREA,B.R_B ORDER BY A.ITEMCODE  
	 END  
 END
END    