SELECT ITEMCODE,ITEMNAME,ISNULL(PRATE,0) AS PRATE,ISNULL(RATE1,0) AS RATE, ISNULL(MRP,0) MRP, ISNULL(CATEGORY,'') CATEGORY,Manufacture,     
 ISNULL(MinOrderAlert,0) MinOrderAlert,    
 CAST(ISNULL(MinOrderAlert,0) AS NVARCHAR(5)) + ' ' + PACKINGTYPE as [Description],    
 ISNULL(CAST((STOCK/TOTALITEMSINPACK) AS NVARCHAR(10) ) + '' + CAST(LEFT(PACKINGTYPE, 1) AS CHAR(1)) + ' ( ' + CAST(STOCK%TOTALITEMSINPACK AS NVARCHAR(10))+ 'p )','') AS QTY,     
 ISNULL(STOCK,0) AS STOCK FROM BELL_ITEMMASTER where Status='Active'     
 
 AND (STOCK/TOTALITEMSINPACK) <= MINORDERALERT  
 AND CATEGORY in ('RAW MATERIALS')  ORDER BY ITEMCODE

 10*12 + 5
 SELECT 125%12 

 SELECT ITEMCODE,ITEMNAME,ISNULL(PRATE,0) AS PRATE,ISNULL(RATE1,0) AS RATE, ISNULL(MRP,0) MRP, ISNULL(CATEGORY,'') CATEGORY,  
 Manufacture, ISNULL(MinOrderAlert,0) MinOrderAlert, CAST(ISNULL(MinOrderAlert,0) AS NVARCHAR(5)) + ' ' + PACKINGTYPE as [Description],    
 ISNULL(CAST((ROUND(STOCK/TOTALITEMSINPACK,0)) AS NVARCHAR(10) ) + ' ' + CAST(LEFT(PACKINGTYPE, 1) AS CHAR(1)) + '(' + CAST(TOTALITEMSINPACK AS NVARCHAR(10))+ ')','') AS QTY,     
 PACKINGTYPE,STOCK/TOTALITEMSINPACK AS CARTONS,STOCK%TOTALITEMSINPACK AS PACKETS,
 ISNULL(STOCK,0) AS STOCK FROM BELL_ITEMMASTER where Status='Active'  ORDER BY ITEMCODE
 
 select * FROM BELL_ITEMMASTER 

-- BELL_STOCK_DETAILS 'ALL','all'    
-- BELL_STOCK_DETAILS 'MINORDER','[NAMKEEN]'    
-- BELL_STOCK_DETAILS 'All','[RAW MATERIALS]'   
-- BELL_STOCK_DETAILS 'ALL','[SWEETS],[BISCUITES]'    
-- BELL_STOCK_DETAILS 'MINORDER','[RAW MATERIALS]'    
alter PROCEDURE BELL_STOCK_DETAILS  
@TYPE as Varchar(10) ,  
@CATEGORY as nvarchar(max)  
AS      
BEGIN  
DECLARE @script AS NVARCHAR(max), @query2 AS NVARCHAR(max)  
set @query2 = ''  
 --CAST(LEFT(PACKINGTYPE, 1) AS CHAR(1)) + '(' + CAST(TOTALITEMSINPACK AS NVARCHAR(4))+ ')' AS QTY,     
if lower(@CATEGORY) <> 'all'      
begin      
  set @query2 = ' AND CATEGORY in (' + REPLACE(REPLACE(@CATEGORY,'[',''''),']','''') + N') '      
end  
  
if lower(@TYPE) = 'all'    
BEGIN     
 
 set @script = N' SELECT ITEMCODE,ITEMNAME,ISNULL(PRATE,0) AS PRATE,ISNULL(RATE1,0) AS RATE, ISNULL(MRP,0) MRP, ISNULL(CATEGORY,'''') CATEGORY, ISNULL(Manufacture,'''') Manufacture,    
 ISNULL(MinOrderAlert,0) MinOrderAlert, isnull(TOTALITEMSINPACK,0) TOTALITEMSINPACK,
 CAST(ISNULL(MinOrderAlert,0) AS NVARCHAR(5)) + '' '' + PACKINGTYPE as [Description],    
 ISNULL(CAST((STOCK/TOTALITEMSINPACK) AS NVARCHAR(10) ) + '''' + CAST(LEFT(PACKINGTYPE, 1) AS CHAR(1)) + '' ('' + CAST(STOCK%TOTALITEMSINPACK AS NVARCHAR(10))+ ''P) '','''') AS QTY,     
 PACKINGTYPE,STOCK/TOTALITEMSINPACK AS CARTONS,STOCK%TOTALITEMSINPACK AS PACKETS,
 ISNULL(STOCK,0) AS STOCK FROM BELL_ITEMMASTER where Status=''Active'' ' + @query2  + ' ORDER BY ITEMCODE'
  
--AND CATEGORY = (case lower(@CATEGORY) when 'all' then CATEGORY ELSE @CATEGORY END)  
END    
ELSE    -- to view only stock less than min order
BEGIN    
 set @script = N' SELECT ITEMCODE,ITEMNAME,ISNULL(PRATE,0) AS PRATE,ISNULL(RATE1,0) AS RATE, ISNULL(MRP,0) MRP, ISNULL(CATEGORY,'''') CATEGORY, ISNULL(Manufacture,'''') Manufacture, 
 ISNULL(MinOrderAlert,0) MinOrderAlert,isnull(TOTALITEMSINPACK,0) TOTALITEMSINPACK,    
 CAST(ISNULL(MinOrderAlert,0) AS NVARCHAR(5)) + '' '' + PACKINGTYPE as [Description],    
 ISNULL(CAST((STOCK/TOTALITEMSINPACK) AS NVARCHAR(10) ) + '''' + CAST(LEFT(PACKINGTYPE, 1) AS CHAR(1)) + '' ('' + CAST(STOCK%TOTALITEMSINPACK AS NVARCHAR(10))+ ''P) '','''') AS QTY,     
 PACKINGTYPE,STOCK/TOTALITEMSINPACK AS CARTONS,STOCK%TOTALITEMSINPACK AS PACKETS,
 ISNULL(STOCK,0) AS STOCK FROM BELL_ITEMMASTER where Status=''Active''     
 AND (STOCK/TOTALITEMSINPACK) <= MINORDERALERT ' + @query2   + ' ORDER BY ITEMCODE'
END  
  
print @query2     
print @script      
EXEC sp_executesql @script  
  
END  