
-- BELL_GET_INACTIVE_SHOPS 'BAYYARAM ','2025-01-15','2025-01-26'
ALTER Procedure BELL_GET_INACTIVE_SHOPS  
@AREA as varchar(30),  
@BILLDATE1 AS DATE,  
@BILLDATE2 AS DATE  
AS               
BEGIN    
 IF (ISNULL(@BILLDATE1,'') <> '' )  
 BEGIN    
  with CTE_SHOPS (AREA,SHOPNAME,AMOUNT)   
  as(  
   select A.AREA,A.SHOPNAME,SUM(AMOUNT) FROM bhavani_ER_Bills A where A.AREA=@AREA AND  
   (A.BILLDATE BETWEEN CONVERT(nvarchar(10),@BILLDATE1,101) AND CONVERT(nvarchar(10),@BILLDATE2,101))    
   GROUP BY AREA,SHOPNAME  
  )   
  SELECT C.AREA,C.SHOPNAME,ISNULL(C.SALESMAN,'') SALESMAN,isnull(LandMark,'') LandMark,Mobile FROM Bell_Cust_Master C   
  WHERE C.SHOPNAME NOT IN (SELECT SHOPNAME FROM CTE_SHOPS) AND C.AREA = @AREA  
  
 END  
END    