SELECT * FROM BELL_LS  WHERE USERNAME='ORDERS' 
,'KOTHAGUDA'
SELECT * FROM bhavani_ER_Bills WHERE AREA IN ('ASIFABAD') 
AND BILLDATE >= CONVERT(nvarchar(10),'2024-08-10',102) AND BILLDATE <= CONVERT(nvarchar(10),'2024-08-25',102)

-- BELL_GET_PENDING_ORDERS 'pendingbills','yes'
-- BELL_GET_PENDING_ORDERS 'pendingbills','no'
-- BELL_GET_PENDING_ORDERS 'orders','yes'
-- BELL_GET_PENDING_ORDERS 'orders','no'
ALTER PROCEDURE BELL_GET_PENDING_ORDERS
@TYPE as Varchar(20) ,    
@GROUPBYLINE as Varchar(3) = ''    
AS        
--@BILLDATE1 AS DATE,        @BILLDATE2 AS DATE,
BEGIN    
DECLARE @script AS NVARCHAR(max), @query2 AS NVARCHAR(max)    

-- ** DELETE ALL WITH USERNAME='RAJU' AND NULL FROM BELL_LS
if lower(@TYPE) = 'pendingbills'      
BEGIN       
IF LOWER(@GROUPBYLINE) = 'yes'
BEGIN
	PRINT 'Pending Bills with Group by Line...'
	-- IF TOTALITEMSINPACK IS REQUIRED THEN NEED TO JOIN ITEM_MASTER
	SELECT ITEMCODE,ITEMNAME,ISNULL(SUM(T_B),0) AS TOTAL_PACKS,ISNULL(SUM(R_B),0) AS RETURN_PACKS,ISNULL(SUM(D_B),0) AS DAMAGE_PACKS
	,FORMAT(BILLDATE, 'dd-MMM-yyyy') AS BILLDATE,AREA AS LINE,USERNAME FROM BELL_LS A
	WHERE (SELECT COUNT(1) FROM bhavani_ER_Bills B WHERE B.BILLDATE > CONVERT(nvarchar(10),'2025-02-25',102) AND B.AREA=A.AREA AND 
	CONVERT(nvarchar(10),B.BILLDATE,102)=CONVERT(nvarchar(10),A.BILLDATE,102) ) = 0
	AND USERNAME IS NOT NULL AND USERNAME NOT IN ('RAJU','ORDERS') 	AND BILLDATE > CONVERT(nvarchar(10),'2025-02-25',102)
	GROUP BY AREA,ITEMCODE,ITEMNAME,RATE,BILLDATE,USERNAME
	ORDER BY BILLDATE,AREA,ITEMCODE
END
ELSE
BEGIN
	PRINT 'Pending Bills without Group by...'
	SELECT ITEMCODE,ITEMNAME,ISNULL(SUM(T_B),0) AS TOTAL_PACKS,ISNULL(SUM(R_B),0) AS RETURN_PACKS,ISNULL(SUM(D_B),0) AS DAMAGE_PACKS
	,'' BILLDATE,'' AS LINE,'' USERNAME
	FROM BELL_LS A
	WHERE (SELECT COUNT(1) FROM bhavani_ER_Bills B WHERE B.BILLDATE > CONVERT(nvarchar(10),'2025-02-25',102) AND B.AREA=A.AREA AND 
	CONVERT(nvarchar(10),B.BILLDATE,102)=CONVERT(nvarchar(10),A.BILLDATE,102) ) = 0
	AND USERNAME IS NOT NULL AND USERNAME NOT IN ('RAJU','ORDERS') AND BILLDATE > CONVERT(nvarchar(10),'2025-02-25',102)
	GROUP BY ITEMCODE,ITEMNAME ORDER BY ITEMCODE
END

END      
ELSE IF lower(@TYPE) = 'orders' 
BEGIN      
IF LOWER(@GROUPBYLINE) = 'yes'
BEGIN
	PRINT 'Orders Placed with Group by...'
	SELECT ITEMCODE,ITEMNAME,ISNULL(SUM(T_B),0) AS TOTAL_PACKS,ISNULL(SUM(R_B),0) AS RETURN_PACKS,ISNULL(SUM(D_B),0) AS DAMAGE_PACKS
	,FORMAT(BILLDATE, 'dd-MMM-yyyy') AS BILLDATE,AREA AS LINE,USERNAME FROM BELL_LS  WHERE USERNAME='ORDERS' 
	AND BILLDATE > CONVERT(nvarchar(10),'2025-02-25',102)
	--AND (BILLDATE BETWEEN CONVERT(nvarchar(10),'2025-01-01',102) AND CONVERT(nvarchar(10),'2025-01-31',102))
	GROUP BY AREA,ITEMCODE,ITEMNAME,BILLDATE,USERNAME ORDER BY BILLDATE,AREA,ITEMCODE
END
ELSE
BEGIN
	PRINT 'Orders Placed without Group by...'
	SELECT ITEMCODE,ITEMNAME,ISNULL(SUM(T_B),0) AS TOTAL_PACKS,ISNULL(SUM(R_B),0) AS RETURN_PACKS,ISNULL(SUM(D_B),0) AS DAMAGE_PACKS
	,'' BILLDATE,'' AS LINE,'' USERNAME 
	FROM BELL_LS  WHERE USERNAME='ORDERS'	
	AND BILLDATE > CONVERT(nvarchar(10),'2025-02-25',102)
	GROUP BY ITEMCODE,ITEMNAME ORDER BY ITEMCODE
END

END
    
END 