--select * from BELL_DAILYCASHFLOW where paiddate='20250329'
--select * from tblVANSALESBILL_DETAILS where billdate='20250329'

ALTER PROCEDURE BELL_DEL_CASH_TRANS_BY_ID
@CASHID AS INT,
@FLAGTYPE AS VARCHAR(15),  -- EXTRA FOR DIFF REPORTS
@result int OUTPUT    
AS
BEGIN
	IF @FLAGTYPE = 'CASH-IN'		
	BEGIN
			IF (SELECT COUNT(1) FROM BELL_DAILYCASHFLOW WHERE ID=@CASHID AND STATUS='PENDING') > 0 
			BEGIN
					DELETE FROM tblVANSALESBILL_DETAILS WHERE CASHID=@CASHID
					DELETE FROM tblVANCASH_IN_DETAILS  WHERE CASHID=@CASHID
					DELETE FROM tblVANCASH_OUT_DETAILS WHERE CASHID=@CASHID
					DELETE FROM BELL_DAILYCASHFLOW WHERE ID=@CASHID
					Delete from BELL_LineSalesManPayments WHERE CASHID=@CASHID
					--tblLineSalesManPendings
					--BELL_LineSalesManPayments
					SET @result = 1
			END
			ELSE
			BEGIN
					SET @result = 0
			END
			SELECT @result
	END
end