CREATE PROCEDURE BELL_SAVE_PENDING_DUES
@FIELDTYPE AS VARCHAR(30),
@ID AS INT,
@RECEIVED AS VARCHAR(3)
AS
BEGIN
-- TO UPDATE RECEIVED FIELD FOR PENDING DUES 
	IF @FIELDTYPE = 'PENDINGDUES'
	BEGIN
			update tblLineSalesManPendings  set Received=@RECEIVED, Actiondate=getdate()  where ID=@ID
	END
	IF @FIELDTYPE = 'ONLINEPAYMENTS'
	BEGIN
			update tblVANCASH_IN_DETAILS set Received=@RECEIVED, Actiondate=getdate()   where ID=@ID
	END
END
