--delete from bell_ls_orders  where area='YELLAREDDYPETA ' 
select * from bell_ls WHERE AREA like '%YELLAREDDYPETA%' AND BILLDATE = '2025-12-02' 
--DELETE FROM bell_ls WHERE AREA like '%YELLAREDDYPETA%' AND BILLDATE = '2025-12-02' 
select * from bell_ls_orders WHERE AREA like '%YELLAREDDYPETA%' AND BILLDATE = '2025-12-02' and ITEMCODE=101 AND ITEMNAME='KRAZY KRAZY(CRAKER) 5 RS' 
select * from bell_ls_orders where area='YELLAREDDYPETA ' AND ITEMNAME in ('KRAZY KRAZY(CRAKER) 5 RS','MARIE SUMO 5 RS','MILKVITA 5 RS','HI-FUN(CREAM)5 RS','CAKE 1RS')
select * from Bell_ItemMaster where ITEMNAME in ('KRAZY KRAZY(CRAKER) 5 RS','KRAZY KRAZY(CRAKER) 3 RS','MARIE SUMO 5 RS','MILKVITA 5 RS','HI-FUN(CREAM)5 RS','CAKE 1RS')
select * from Bell_LS where ITEMNAME in ('KRAZY KRAZY(CRAKER) 5 RS','KRAZY KRAZY(CRAKER) 3 RS','MARIE SUMO 5 RS','MILKVITA 5 RS','HI-FUN(CREAM)5 RS','CAKE 1RS')

insert into BELL_LS_ORDERS (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B)         
				values(101,'KRAZY KRAZY(CRAKER) 5 RS',35.71,'23P (1)','2025-Dec-02','YELLAREDDYPETA ','ORDERS',23)        
UPDATE BELL_LS_ORDERS SET RATE=35.71,QTY='45C (14)',USERNAME='ORDERS',T_B=630,ACTIONDATE=GETDATE() WHERE        
			ITEMCODE=101 AND ITEMNAME='KRAZY KRAZY(CRAKER) 5 RS' AND AREA='YELLAREDDYPETA' AND CONVERT(varchar(10),BILLDATE,101) = '2025-12-02'

select CONVERT(varchar(10),'2025-12-02',101) 
/*     declare @BILLDATE as DATE
     set @BILLDATE='22/Apr/2025'
  SELECT CONVERT(varchar(10),BILLDATE,101) ,* FROM BELL_LS WHERE AREA='CHENNURU' AND USERNAME='tejaswini'  --ORDER BY BILLDATE DESC
  AND 
  CONVERT(varchar(10),BILLDATE,101) = CONVERT(varchar(10),@BILLDATE,101)
  */
ALTER procedure BELL_INC_UPD_LS_ITEMS_NEW      
@BILLDATE as DATE,      
@AREA as varchar(30),      
@ITEMCODE AS integer,      
@ITEMNAME AS VARCHAR(30),      
@PRICE AS VARCHAR(10),      
@QTY AS VARCHAR(10),      
@T_B AS integer,      
@R_B AS INTeger,      
@D_B AS integer,      
@USERNAME AS VARCHAR(30),      
@result int OUTPUT      
      
AS                   
BEGIN      
 SET @result = 0    
 set @BILLDATE = CONVERT(varchar(10),@BILLDATE,101)      
 DECLARE @PREVIOUS_PACKETS AS INTEGER,@NEW_PACKETS AS INTEGER    
 SET @NEW_PACKETS = @T_B - @R_B - @D_B    
 
	-- to insert data to orders table only if the request is from Orders system ON 04-DEC-2025
 if @USERNAME = 'ORDERS' 
  BEGIN
		iF (SELECT COUNT(1) FROM BELL_LS_ORDERS WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND AREA=@AREA AND CONVERT(varchar(10),BILLDATE,101) = @BILLDATE) = 0       
		begin
				insert into BELL_LS_ORDERS (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B)         
				values(@ITEMCODE,@ITEMNAME,@PRICE,@QTY,@BILLDATE,@AREA,@USERNAME,@T_B)        
		end
		ELSE
		BEGIN			
			UPDATE BELL_LS_ORDERS SET RATE=@PRICE,QTY=@QTY,USERNAME=@USERNAME,T_B=@T_B,ACTIONDATE=GETDATE() WHERE        
			ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND AREA=@AREA AND BILLDATE = @BILLDATE                
		END
 END
  iF (SELECT COUNT(1) FROM BELL_LS WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND AREA=@AREA AND CONVERT(varchar(10),BILLDATE,101) = @BILLDATE) = 0       
 BEGIN      
		  --PRINT 'NO COUNT'      
		   insert into BELL_LS (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B,R_B,D_B)       
		   values(@ITEMCODE,@ITEMNAME,@PRICE,@QTY,@BILLDATE,@AREA,@USERNAME,@T_B,@R_B,@D_B)      		
		-- FOR orders, no need to update stock count.  
		 if @USERNAME <> 'ORDERS'  
		 BEGIN  
		  UPDATE BELL_ITEMMASTER SET STOCK=STOCK-@NEW_PACKETS,USERNAME=@USERNAME,ACTIONDATE=GETDATE() WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME    
		 END  
  END      
  ELSE      
  BEGIN      
		SELECT @PREVIOUS_PACKETS=T_B-R_B-D_B FROM BELL_LS WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND AREA=@AREA AND BILLDATE = @BILLDATE
		--print @PREVIOUS_PACKETS
		UPDATE BELL_LS SET RATE=@PRICE,QTY=@QTY,USERNAME=@USERNAME,T_B=@T_B,R_B=@R_B,D_B=@D_B,ACTIONDATE=GETDATE() WHERE      
        ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND AREA=@AREA AND CONVERT(varchar(10),BILLDATE,101) = @BILLDATE		
   -- FOR orders, no need to update stock count.  
	   if @USERNAME <> 'ORDERS'  
	   BEGIN  
	   --update stock value in ItemMaster, by removing previous stock and updating with new value     
	   UPDATE BELL_ITEMMASTER SET STOCK=STOCK + @PREVIOUS_PACKETS - @NEW_PACKETS,USERNAME=@USERNAME,ACTIONDATE=GETDATE() WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME    
	  END  
  END      
    SET @result = 1      
   SELECT @result AS RESULT      
END 