CREATE procedure BELL_INC_UPD_LS_ITEMS  
@BILLDATE as DATE,  
@AREA as varchar(30),  
@ITEMCODE AS integer,  
@ITEMNAME AS VARCHAR(30),  
@PRICE AS VARCHAR(5),  
@QTY AS VARCHAR(10),  
@T_B AS integer,  
@R_B AS INTeger,  
@D_B AS integer,  
@USERNAME AS VARCHAR(30),  
@result int OUTPUT  
  
AS               
BEGIN  
 set @BILLDATE = CONVERT(varchar(10),@BILLDATE,101)  
  
  iF (SELECT COUNT(1) FROM BELL_LS WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND AREA=@AREA AND CONVERT(varchar(10),BILLDATE,101) = @BILLDATE) = 0   
 BEGIN  
  PRINT 'NO COUNT'  
   insert into BELL_LS (ITEMCODE,ITEMNAME,RATE,QTY,BILLDATE,AREA,USERNAME,T_B,R_B,D_B)   
   values(@ITEMCODE,@ITEMNAME,@PRICE,@QTY,@BILLDATE,@AREA,@USERNAME,@T_B,@R_B,@D_B)  
  END  
  ELSE  
  BEGIN  
    PRINT 'RECORD EXIST'  
    SELECT * FROM BELL_LS WHERE ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND AREA=@AREA AND CONVERT(varchar(10),BILLDATE,101) = @BILLDATE  
      UPDATE BELL_LS SET RATE=@PRICE,QTY=@QTY,USERNAME=@USERNAME,T_B=@T_B,R_B=@R_B,D_B=@D_B WHERE  
        ITEMCODE=@ITEMCODE AND ITEMNAME=@ITEMNAME AND AREA=@AREA AND CONVERT(varchar(10),BILLDATE,101) = @BILLDATE          
  END  
    SET @result = 1  
   SELECT @result AS RESULT  
END  