CREATE procedure BELL_UPSERT_MOBILE_SHOP_VISITING_INFO
@LINE as varchar(50),
@AREA as varchar(50),
@SHOPNAME AS VARCHAR(50),            
@ORDERDATE as DATETIME,
@SHOP_VISIT_STATUS AS VARCHAR(50),            
@SALESMAN AS nvarchar(30)=''
AS                         
BEGIN            

  iF (SELECT COUNT(1) FROM BELL_APP_SHOPS_VISIT_INFO WHERE LINE=@LINE AND AREA=@AREA AND SHOPNAME=@SHOPNAME         
     AND ORDERDATE = @ORDERDATE) = 0              
 BEGIN            
    insert into BELL_APP_SHOPS_VISIT_INFO
    (LINE,AREA,SHOPNAME,SHOP_VISIT_STATUS,SALESMAN,ORDERDATE) VALUES (
    @LINE,@AREA,@SHOPNAME,@SHOP_VISIT_STATUS,@SALESMAN,@ORDERDATE)   
END
 ELSE            
 BEGIN            
        UPDATE BELL_APP_SHOPS_VISIT_INFO SET  LINE=@LINE,AREA=@AREA,SHOPNAME=@SHOPNAME,SALESMAN=@SALESMAN,
        SHOP_VISIT_STATUS=@SHOP_VISIT_STATUS,ORDERDATE=@ORDERDATE, ACTIONDATE=GETDATE()
      WHERE LINE=@LINE AND AREA=@AREA AND SHOPNAME=@SHOPNAME AND ORDERDATE=@ORDERDATE 
 END
   SELECT 1 AS RESULT            
END 