Create Procedure USP_Update_ItemDetails  
@ID as varchar(30),  
@ITEMNAME as varchar(30),  
@RATE as Money,  
@MRP as INT,  
@PACKINGTYPE AS varchar(20),  
@TOTALITEMSINPACK AS varchar(10),  
@TOTALITEMSINCARTON as varchar(10),  
@CATEGORY as varchar(20),  
@DESCRIPTION AS varchar(30),  
@IMAGEURL AS VARCHAR(50)  
AS             
BEGIN  
 --declare @ImageURL as varchar(50)  
 --set @ImageURL = (Select top 1 FieldValue from tblAllMasterData where FieldType='ImageServerURL')  
 if @ID > 0   
 BEGIN  
 UPDATE TBLITEMMASTER SET ITEMNAME=@ITEMNAME,MRP=@MRP,RATE=@RATE,PACKINGTYPE=@PACKINGTYPE,  
 TOTALITEMSINPACK=@TOTALITEMSINPACK,TOTALITEMSINCARTON=@TOTALITEMSINCARTON,CATEGORY=@CATEGORY,  
 [DESCRIPTION]=@DESCRIPTION WHERE ITEMID=@ID    
 --IMAGEURL=@IMAGEURL,  
 END  
 ELSE  
 BEGIN  
  INSERT INTO TBLITEMMASTER (ITEMNAME,MRP,RATE,PACKINGTYPE,TOTALITEMSINPACK,TOTALITEMSINCARTON,CATEGORY,[DESCRIPTION],ImageUrl)  
  VALUES(@ITEMNAME,@MRP,@RATE,@PACKINGTYPE,@TOTALITEMSINPACK,@TOTALITEMSINCARTON,@CATEGORY,@DESCRIPTION,@IMAGEURL)     
 END  
END  