/*
SELECT * FROM BELL_USERS 
USP_VALIDATE_USER   'king','SuperUser@2312','admin'

*/

alter procedure USP_VALIDATE_USER  
@USERNAME as varchar(20),  
@PASSWORD as varchar(20),  
@USERTYPE as varchar(20)  
AS  
Begin   
 SELECT ID,USERNAME,STATUS,USERTYPE,FIRSTNAME,LASTNAME FROM BELL_USERS WHERE USERNAME=@USERNAME AND PASSWORD=@PASSWORD AND USERTYPE=@USERTYPE  and STATUS='Active'
 --IF (EXISTS (SELECT 'X' FROM BELL_USERS WHERE USERNAME=@USERNAME AND PWD=@PWD AND USERTYPE=@USERTYPE))  
 --Begin  
 -- Select 'VALID'  
 --end  
 --else  
 --BEGIN  
 -- Select 'INVALID'  
 --END  
End  